version: "3"

services:
  app_gestor:
    image: mbamobi/ionicapp:node9
    depends_on:
      - api
    environment:
      SERVER_NAME: gestor.mseventos.mbamobi.com.br
      DEMO_MODE: 'no'
      GIT_TOKEN: 08c170bcb71588809a4d3440bd5644bcc59d9897
    volumes:
      - /data/ms_eventos_gestor:/var/source
      - /data/ms_eventos_gestor/api/config/supervisord.d:/etc/supervisord.d
      - /root/android-sdk-linux:/root/android-sdk-linux
      - /data/mba_build_config:/var/mba_build_config
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.backend=app_gestor"
        - "traefik.frontend.rule=Host:gestor.mseventos.mbamobi.com.br"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

  api:
    image: mbamobi/loopbackapi:node7
    ports:
      - 3000:3000
    depends_on:
      - oracledb
    environment:
      SERVER_NAME: api.mseventos.mbamobi.com.br
      DEMO_MODE: 'no'
      GIT_TOKEN: 08c170bcb71588809a4d3440bd5644bcc59d9897
      NODE_VERSION: 7.8.0
      NPM_VERSION: 5.5.1
    volumes:  
      - /data/ms_eventos_gestor/api:/var/source
      - /data/ms_eventos_gestor/api/config/supervisord.d:/etc/supervisord.d
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.port=3000"
        - "traefik.backend=api"
        - "traefik.frontend.rule=Host:api.mseventos.mbamobi.com.br"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

  oracledb:
    image: sath89/oracle-xe-11g
    environment:
      DEFAULT_SYS_PASS: mbamobi
    ports:
      - 1521:1521
    volumes:
      - /data/oracle:/u01/app/oracle
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

  jenkins:
    image: jenkins:alpine
    ports:
      - 8081:8081
      - 50000:50000
    depends_on:
      - api
    environment:
      JENKINS_PORT: 8081
      JENKINS_OPTS: --httpPort=8081
    volumes:
      - /data/jenkins:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=8081"
        - "traefik.backend=jenkins"
        - "traefik.frontend.rule=Host:ci.mseventos.mbamobi.com.br"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

networks:
  internal:
  proxy:
    external: true
