version: "3"

services:
  oracle:
    image: sath89/oracle-xe-11g
    environment:
      DEFAULT_SYS_PASS: mbamobi
    ports:
      - 1521:1521
    volumes:
      - /data/oracle:/u01/app/oracle
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.hostname == ms-docker-leader
    networks:
      - internal
      - proxy

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mbamobi
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.hostname == ms-docker-leader
    networks:
      - internal
      - proxy

networks:
  internal:
  proxy:
    external: true