version: "3"

services:
  app_gestor:
    image: mbamobi/ionicapp:node7
    depends_on:
      - api
    environment:
      SERVER_NAME: eventos-gestor.ms.mbamobi.com.br
      DEMO_MODE: 'no'
      GIT_TOKEN: 08c170bcb71588809a4d3440bd5644bcc59d9897
      NODE_VERSION: 7.8.0
      NPM_VERSION: 5.3.0
    volumes:
      - /data/ms_eventos_gestor:/var/source
      - /data/ms_eventos_gestor/api/config/supervisord.d:/etc/supervisord.d
      - /root/android-sdk-linux:/root/android-sdk-linux
      - /data/mba_build_config:/var/mba_build_config
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.backend=app_gestor"
        - "traefik.frontend.rule=Host:eventos-gestor.ms.mbamobi.com.br"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

  app_participante:
    image: mbamobi/ionicapp:node7
    depends_on:
      - api
    environment:
      SERVER_NAME: eventos-participante.ms.mbamobi.com.br
      DEMO_MODE: 'no'
      GIT_TOKEN: e8b866f4bd2cdec875602a4c0fd4e3080b0eba6c
      NODE_VERSION: 7.8.0
      NPM_VERSION: 5.3.0
    volumes:
      - /data/ms_eventos_participante:/var/source
      - /root/android-sdk-linux:/root/android-sdk-linux
      - /data/mba_build_config:/var/mba_build_config
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.backend=app_participante"
        - "traefik.frontend.rule=Host:eventos-participante.ms.mbamobi.com.br"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

  api:
    image: mbamobi/loopbackapi:node7
    ports:
      - 3000:3000
    depends_on:
      - oracledb
    environment:
      SERVER_NAME: eventos-api.ms.mbamobi.com.br
      GIT_TOKEN: 08c170bcb71588809a4d3440bd5644bcc59d9897
      NODE_VERSION: 7.8.0
      NPM_VERSION: 5.5.1
    volumes:
      - /data/ms_eventos_gestor/api:/var/source
      - /data/ms_eventos_gestor/api/config/supervisord.d:/etc/supervisord.d
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=3000"
        - "traefik.backend=api"
        - "traefik.frontend.rule=Host:eventos-api.ms.mbamobi.com.br"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
    networks:
      - internal
      - proxy

networks:
  internal:
  proxy:
    external: true
