version: "3"

services:
  lb:
    image: traefik:1.3.6-alpine
    command: --docker --docker.swarmmode --docker.watch --web --logLevel=DEBUG
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik.toml:/traefik.toml
      - /data/traefik/acme.json:/acme.json
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:lb.ms.mbamobi.com.br"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.hostname == ms-docker-leader
    networks:
       - proxy

networks:
  proxy:
    external: true